name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:    
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Go
      uses: actions/setup-go@v2

    - name: path
      shell: bash
      run: echo ${PATH} 

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.88.1
        TARGET_REPO: mjunyentb/mjunyentb.github.io
        TOKEN: ${{ secrets.TOKEN }}
